### ISSUE TITLE
dm800sev2 still doesn't work

### ISSUE THREAD

**Issue by gjstroom** [PLi-metas/meta-dream#4]
The dm800sev2 build still doesn't work because it's missing the stv0299 module.
The dm800se does work because stv0299 is not a module in the kernel config (included in the kernel), where it is a module in the dm800sev2 kernel config.
I like things to be consistent, so make stv0299 for both d800se and dm800sev2 kernel modules.

You need to add to dreambox-dvb-modules-dm800se_3.2-20151201.bb
RDEPENDS_${PN} += "kernel-module-stv0299-3.2-dm800se"
and to dreambox-dvb-modules-dm800sev2_3.2-20151201.bb
RDEPENDS_${PN} += "kernel-module-stv0299-3.2-dm800sev2"

**Comment by Hains** [comment]
https://github.com/PLi-metas/meta-dream/commit/8a6bc5eb3803144d1b099606b7307b24ecc54b5d

Is this OK?

**Comment by gjstroom** [comment]
Works for me !

**Comment by Hains** [comment]
Yes i remember from dm8000. It depends on how bitbake packed the kernel modules in combination with OE changes in Pyro.
Anyway i changed it.

**Comment by gjstroom** [comment]
While we are changing some stuff, please also have a look at linux-dreambox.inc.
All the lines with kernel-module-block2mtd aren't necessary because for all boxes they are a static kernel component. But for the dm800 block2mtd  is a module and that's the one not listed (but it does work).

**Comment by Hains** [comment]
It depends how bitbake packed the kernel modules.
If bitbake install them as separate packages, then you need KERNEL_BUILTIN_MODULES  (that's what OpenPLi does with dm8000) and stv-299 needs MACHINE as append.
If bitbake create one package for all modules, then KERNEL_BUILTIN_MODULES is superfluous. But i'm not sure ( we never tested it without).

**Comment by Hains** [comment]
If you sure we can delete KERNEL_BUILTIN_MODULES  for dm800se(v2),  i delete them.

**Comment by Hains** [comment]
It's a long time ago. see this
https://github.com/PLi-metas/meta-dream/commit/15f849f824c4c558a07666e67194f5df2aae5ff8

**Comment by gjstroom** [comment]
This is mine linux-dreambox.inc (part)
#KERNEL_BUILTIN_MODULES = "kernel-module-block2mtd"

KERNEL_BUILTIN_MODULES_dm800 = "\
        kernel-module-block2mtd \
        "
KERNEL_BUILTIN_MODULES_dm8000 = "\
        kernel-module-stv0299 \
        "
KERNEL_BUILTIN_MODULES_dm800se = "\
        kernel-module-stv0299 \
        "
KERNEL_BUILTIN_MODULES_dm800sev2 = "\
        kernel-module-stv0299 \
        "
KERNEL_BUILTIN_MODULES_dm7020hd = "\
        kernel-module-fuse \
        kernel-module-stv0299 \
        "
That works for dm500hd, dm800, dm800se/v2. I don't know for the other dmm boxes.

**Comment by Hains** [comment]
OK, so only dm800 needs it.
I delete kernel-module-block2mtd for dm800se(v2) and dm500hd(v2) first.
I can test dm8000 myself, if box can live without kernel-module-block2mtd i delete it for dm7020hd as well.
When someone complain it can always revert it.

**Comment by Hains** [comment]
Auh.. dm8000 doesn't have it..so i delete it for dm7020hd also.

**Comment by gjstroom** [comment]
I'll try a build with the whole KERNEL_BUILTIN_MODULES section removed. I let you know.

**Comment by gjstroom** [comment]
I did remove all KERNEL_BUILTIN_MODULES lines  from linux-dreambox.inc and with a virgin build all works fine. I only needed to switch to enigma2 rc branch because one of the pli members once again did some untested commits to the develop branch, enigma2 develop goes in a bootloop for now.

**Comment by Hains** [comment]
The changes to Nimmanager? Yeah, that commit is reverted in develop branch.

I tested dm8000 without KERNEL_BUILTIN_MODULES,and no problem at all.
So i can wipe out the whole selection for all boxes.
I'll do that.
Thanks for testing.
